apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-2-speech-deploy
  labels:
    app: say
spec:
  replicas: 3
  selector:
    matchLabels:
      app: say
  template:
    metadata:
      labels:
        app: say
    spec:
      containers:
      - name: say
        image: gcr.io/kubernetes-285020/say
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: text-2-speech-svc
spec:
  selector:
    app: say
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer
    